version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_CONFIG=production
      - DB_HOST=db
      - DB_NAME=enam
      - DB_USER=postgres
      - DB_PASSWORD=mathew
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=enam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mathew
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./python/sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge